INSERT INTO ALMACEN_DB.Categorias (nombre             , fecha_creacion, fecha_actualizacion, concurrencia)
                           VALUES ('Electrónica'      , CURDATE()     , CURDATE()          , 0           ),
                                  ('Hogar y Jardín'   , CURDATE()     , CURDATE()          , 0           ),
                                  ('Ropa y Accesorios', CURDATE()     , CURDATE()          , 0           ),
                                  ('Salud y Belleza'  , CURDATE()     , CURDATE()          , 0           ),
                                  ('Deportes'         , CURDATE()     , CURDATE()          , 0           ),
                                  ('Juguetes'         , CURDATE()     , CURDATE()          , 0           ),
                                  ('Alimentos'        , CURDATE()     , CURDATE()          , 0           ),
                                  ('Automotriz'       , CURDATE()     , CURDATE()          , 0           ),
                                  ('Tecnología'       , CURDATE()     , CURDATE()          , 0           ),
                                  ('Libros'           , CURDATE()     , CURDATE()          , 0           ),
                                  ('Muebles'          , CURDATE()     , CURDATE()          , 0           ),
                                  ('Joyería'          , CURDATE()     , CURDATE()          , 0           ),
                                  ('Mascotas'         , CURDATE()     , CURDATE()          , 0           ),
                                  ('Oficinas'         , CURDATE()     , CURDATE()          , 0           ),
                                  ('Cuidado Personal' , CURDATE()     , CURDATE()          , 0           ),
                                  ('Viajes'           , CURDATE()     , CURDATE()          , 0           ),
                                  ('Fitness'          , CURDATE()     , CURDATE()          , 0           ),
                                  ('Cuidado del Hogar', CURDATE()     , CURDATE()          , 0           ),
                                  ('Manualidades'     , CURDATE()     , CURDATE()          , 0           ),
                                  ('Videojuegos'      , CURDATE()     , CURDATE()          , 0           );

INSERT INTO ALMACEN_DB.Productos (categoria_fk                                                             , nombre                 , descripcion                                              , stock_minimo , fecha_creacion, fecha_actualizacion, concurrencia)
                          VALUES ((SELECT id FROM ALMACEN_DB.Categorias WHERE nombre = 'Electrónica')      , 'Smartphone'           , 'Dispositivo móvil para comunicación y multimedia'       , 5            , CURDATE()     , CURDATE()          , 0           ),
                                 ((SELECT id FROM ALMACEN_DB.Categorias WHERE nombre = 'Electrónica')      , 'Audífonos sin cables' , 'Escucha música o atiende llamadas sin cables'           , 10           , CURDATE()     , CURDATE()          , 0           ),
                                 ((SELECT id FROM ALMACEN_DB.Categorias WHERE nombre = 'Electrónica')      , 'Televisor LED'        , 'Pantalla con alta definición y bajo consumo energético' , 3            , CURDATE()     , CURDATE()          , 0           ),
                                 ((SELECT id FROM ALMACEN_DB.Categorias WHERE nombre = 'Electrónica')      , 'Tableta'              , 'Dispositivo portátil para lectura y entretenimiento'    , 4            , CURDATE()     , CURDATE()          , 0           ),
                                 ((SELECT id FROM ALMACEN_DB.Categorias WHERE nombre = 'Hogar y Jardín')   , 'Aspiradora robótica'  , 'Limpieza autónoma de pisos y alfombras'                 , 2            , CURDATE()     , CURDATE()          , 0           ),
                                 ((SELECT id FROM ALMACEN_DB.Categorias WHERE nombre = 'Hogar y Jardín')   , 'Maceta decorativa'    , 'Elemento de jardinería para embellecer el hogar'        , 15           , CURDATE()     , CURDATE()          , 0           ),
                                 ((SELECT id FROM ALMACEN_DB.Categorias WHERE nombre = 'Hogar y Jardín')   , 'Barbacoa a gas'       , 'Parrilla para asados, fácil de usar'                    , 2            , CURDATE()     , CURDATE()          , 0           ),
                                 ((SELECT id FROM ALMACEN_DB.Categorias WHERE nombre = 'Ropa y Accesorios'), 'Chaqueta de cuero'    , 'Abrigo elegante y duradero para diversas ocasiones'     , 6            , CURDATE()     , CURDATE()          , 0           ),
                                 ((SELECT id FROM ALMACEN_DB.Categorias WHERE nombre = 'Ropa y Accesorios'), 'Bufanda de lana'      , 'Accesorio cálido y suave para el invierno'              , 8            , CURDATE()     , CURDATE()          , 0           ),
                                 ((SELECT id FROM ALMACEN_DB.Categorias WHERE nombre = 'Ropa y Accesorios'), 'Reloj digital'        , 'Reloj moderno con funciones básicas y deportivas'       , 5            , CURDATE()     , CURDATE()          , 0           ),
                                 ((SELECT id FROM ALMACEN_DB.Categorias WHERE nombre = 'Salud y Belleza')  , 'Crema hidratante'     , 'Hidratación profunda para todo tipo de piel'            , 10           , CURDATE()     , CURDATE()          , 0           ),
                                 ((SELECT id FROM ALMACEN_DB.Categorias WHERE nombre = 'Salud y Belleza')  , 'Gel antiséptico'      , 'Protección para manos contra gérmenes'                  , 10           , CURDATE()     , CURDATE()          , 0           ),
                                 ((SELECT id FROM ALMACEN_DB.Categorias WHERE nombre = 'Salud y Belleza')  , 'Set de maquillaje'    , 'Incluye productos esenciales para el maquillaje'        , 5            , CURDATE()     , CURDATE()          , 0           ),
                                 ((SELECT id FROM ALMACEN_DB.Categorias WHERE nombre = 'Deportes')         , 'Bicicleta de montaña' , 'Ideal para aventuras al aire libre y senderismo'        , 3            , CURDATE()     , CURDATE()          , 0           ),
                                 ((SELECT id FROM ALMACEN_DB.Categorias WHERE nombre = 'Deportes')         , 'Pelota de fútbol'     , 'Balón de juego de alta calidad para entrenamiento'      , 7            , CURDATE()     , CURDATE()          , 0           ),
                                 ((SELECT id FROM ALMACEN_DB.Categorias WHERE nombre = 'Juguetes')         , 'Lego de construcción' , 'Juego de bloques para desarrollar la creatividad'       , 10           , CURDATE()     , CURDATE()          , 0           ),
                                 ((SELECT id FROM ALMACEN_DB.Categorias WHERE nombre = 'Juguetes')         , 'Muñeca de acción'     , 'Figura articulada de diversos personajes'               , 5            , CURDATE()     , CURDATE()          , 0           ),
                                 ((SELECT id FROM ALMACEN_DB.Categorias WHERE nombre = 'Alimentos')        , 'Snacks saludables'    , 'Comida ligera , nutritiva y deliciosa'                  , 20           , CURDATE()     , CURDATE()          , 0           ),
                                 ((SELECT id FROM ALMACEN_DB.Categorias WHERE nombre = 'Alimentos')        , 'Café orgánico'        , 'Café de alta calidad , cultivado de forma sostenible'   , 15           , CURDATE()     , CURDATE()          , 0           ),
                                 ((SELECT id FROM ALMACEN_DB.Categorias WHERE nombre = 'Automotriz')       , 'Limpiaparabrisas'     , 'Producto para mantener limpias las ventanas del auto'   , 5            , CURDATE()     , CURDATE()          , 0           ),
                                 ((SELECT id FROM ALMACEN_DB.Categorias WHERE nombre = 'Automotriz')       , 'Kit de herramientas'  , 'Herramientas básicas imprescindibles para reparaciones' , 3            , CURDATE()     , CURDATE()          , 0           );

-- Nomenclatura de ejemplo para los nombre de las ubicaciones:
-- PXEY -> Planta X Estante Y
INSERT INTO ALMACEN_DB.Ubicaciones (nombre , fecha_creacion, fecha_actualizacion, concurrencia)
                            VALUES ('P1E1' , CURDATE()     , CURDATE()          , 0           ),
                                   ('P1E2' , CURDATE()     , CURDATE()          , 0           ),
                                   ('P1E3' , CURDATE()     , CURDATE()          , 0           ),
                                   ('P1E4' , CURDATE()     , CURDATE()          , 0           ),
                                   ('P1E5' , CURDATE()     , CURDATE()          , 0           ),
                                   ('P2E1' , CURDATE()     , CURDATE()          , 0           ),
                                   ('P2E2' , CURDATE()     , CURDATE()          , 0           ),
                                   ('P2E3' , CURDATE()     , CURDATE()          , 0           ),
                                   ('P2E4' , CURDATE()     , CURDATE()          , 0           ),
                                   ('P2E5' , CURDATE()     , CURDATE()          , 0           ),
                                   ('P3E1' , CURDATE()     , CURDATE()          , 0           ),
                                   ('P3E2' , CURDATE()     , CURDATE()          , 0           ),
                                   ('P3E3' , CURDATE()     , CURDATE()          , 0           ),
                                   ('P3E4' , CURDATE()     , CURDATE()          , 0           ),
                                   ('P3E5' , CURDATE()     , CURDATE()          , 0           ),
                                   ('P4E1' , CURDATE()     , CURDATE()          , 0           ),
                                   ('P4E2' , CURDATE()     , CURDATE()          , 0           ),
                                   ('P4E3' , CURDATE()     , CURDATE()          , 0           ),
                                   ('P4E4' , CURDATE()     , CURDATE()          , 0           ),
                                   ('P4E5' , CURDATE()     , CURDATE()          , 0           );

-- Nomenclatura de ejemplo para los nombres de las ventas:
-- VTA-YYYYMMDD-XXX -> Venta del día YYYY-MM-DD número XXX
INSERT INTO ALMACEN_DB.Ventas (nombre            , fecha_creacion, fecha_actualizacion, concurrencia)
                       VALUES ('VTA-20250101-001', CURDATE()     , CURDATE()          , 0           ),
                              ('VTA-20250115-001', CURDATE()     , CURDATE()          , 0           ),
                              ('VTA-20250115-002', CURDATE()     , CURDATE()          , 0           ),
                              ('VTA-20250202-001', CURDATE()     , CURDATE()          , 0           ),
                              ('VTA-20250214-001', CURDATE()     , CURDATE()          , 0           ),
                              ('VTA-20250301-001', CURDATE()     , CURDATE()          , 0           ),
                              ('VTA-20250315-001', CURDATE()     , CURDATE()          , 0           ),
                              ('VTA-20250401-001', CURDATE()     , CURDATE()          , 0           ),
                              ('VTA-20250410-001', CURDATE()     , CURDATE()          , 0           ),
                              ('VTA-20250420-001', CURDATE()     , CURDATE()          , 0           );

INSERT INTO ALMACEN_DB.Ejemplares (producto_fk                                                                , ubicacion_fk                                                 , venta_fk                                                            , precio, fecha_entrada, fecha_actualizacion, concurrencia)
                           VALUES ((SELECT id FROM ALMACEN_DB.Productos WHERE nombre = 'Smartphone')          , (SELECT id FROM ALMACEN_DB.Ubicaciones WHERE nombre = 'P1E1'), (SELECT id FROM ALMACEN_DB.Ventas WHERE nombre = 'VTA-20250101-001'), 699   , CURDATE()    , CURDATE()          , 0           ),
                                  ((SELECT id FROM ALMACEN_DB.Productos WHERE nombre = 'Smartphone')          , (SELECT id FROM ALMACEN_DB.Ubicaciones WHERE nombre = 'P1E1'), (SELECT id FROM ALMACEN_DB.Ventas WHERE nombre = 'VTA-20250202-001'), 749   , CURDATE()    , CURDATE()          , 0           ),
                                  ((SELECT id FROM ALMACEN_DB.Productos WHERE nombre = 'Smartphone')          , (SELECT id FROM ALMACEN_DB.Ubicaciones WHERE nombre = 'P1E2'), NULL                                                                , 799   , CURDATE()    , CURDATE()          , 0           ),
                                  ((SELECT id FROM ALMACEN_DB.Productos WHERE nombre = 'Audífonos sin cables'), (SELECT id FROM ALMACEN_DB.Ubicaciones WHERE nombre = 'P1E3'), (SELECT id FROM ALMACEN_DB.Ventas WHERE nombre = 'VTA-20250115-001'), 89    , CURDATE()    , CURDATE()          , 0           ),
                                  ((SELECT id FROM ALMACEN_DB.Productos WHERE nombre = 'Audífonos sin cables'), (SELECT id FROM ALMACEN_DB.Ubicaciones WHERE nombre = 'P1E3'), NULL                                                                , 99    , CURDATE()    , CURDATE()          , 0           ),
                                  ((SELECT id FROM ALMACEN_DB.Productos WHERE nombre = 'Televisor LED')       , (SELECT id FROM ALMACEN_DB.Ubicaciones WHERE nombre = 'P2E1'), (SELECT id FROM ALMACEN_DB.Ventas WHERE nombre = 'VTA-20250115-002'), 1299  , CURDATE()    , CURDATE()          , 0           ),
                                  ((SELECT id FROM ALMACEN_DB.Productos WHERE nombre = 'Televisor LED')       , (SELECT id FROM ALMACEN_DB.Ubicaciones WHERE nombre = 'P2E2'), NULL                                                                , 1399  , CURDATE()    , CURDATE()          , 0           ),
                                  ((SELECT id FROM ALMACEN_DB.Productos WHERE nombre = 'Tableta')             , (SELECT id FROM ALMACEN_DB.Ubicaciones WHERE nombre = 'P1E4'), NULL                                                                , 449   , CURDATE()    , CURDATE()          , 0           ),
                                  ((SELECT id FROM ALMACEN_DB.Productos WHERE nombre = 'Maceta decorativa')   , (SELECT id FROM ALMACEN_DB.Ubicaciones WHERE nombre = 'P3E1'), (SELECT id FROM ALMACEN_DB.Ventas WHERE nombre = 'VTA-20250214-001'), 25    , CURDATE()    , CURDATE()          , 0           ),
                                  ((SELECT id FROM ALMACEN_DB.Productos WHERE nombre = 'Maceta decorativa')   , (SELECT id FROM ALMACEN_DB.Ubicaciones WHERE nombre = 'P3E1'), (SELECT id FROM ALMACEN_DB.Ventas WHERE nombre = 'VTA-20250301-001'), 25    , CURDATE()    , CURDATE()          , 0           ),
                                  ((SELECT id FROM ALMACEN_DB.Productos WHERE nombre = 'Maceta decorativa')   , (SELECT id FROM ALMACEN_DB.Ubicaciones WHERE nombre = 'P3E2'), NULL                                                                , 30    , CURDATE()    , CURDATE()          , 0           ),
                                  ((SELECT id FROM ALMACEN_DB.Productos WHERE nombre = 'Maceta decorativa')   , (SELECT id FROM ALMACEN_DB.Ubicaciones WHERE nombre = 'P3E2'), NULL                                                                , 30    , CURDATE()    , CURDATE()          , 0           ),
                                  ((SELECT id FROM ALMACEN_DB.Productos WHERE nombre = 'Chaqueta de cuero')   , (SELECT id FROM ALMACEN_DB.Ubicaciones WHERE nombre = 'P2E3'), (SELECT id FROM ALMACEN_DB.Ventas WHERE nombre = 'VTA-20250315-001'), 199   , CURDATE()    , CURDATE()          , 0           ),
                                  ((SELECT id FROM ALMACEN_DB.Productos WHERE nombre = 'Chaqueta de cuero')   , (SELECT id FROM ALMACEN_DB.Ubicaciones WHERE nombre = 'P2E4'), NULL                                                                , 219   , CURDATE()    , CURDATE()          , 0           ),
                                  ((SELECT id FROM ALMACEN_DB.Productos WHERE nombre = 'Reloj digital')       , (SELECT id FROM ALMACEN_DB.Ubicaciones WHERE nombre = 'P2E5'), (SELECT id FROM ALMACEN_DB.Ventas WHERE nombre = 'VTA-20250401-001'), 79    , CURDATE()    , CURDATE()          , 0           ),
                                  ((SELECT id FROM ALMACEN_DB.Productos WHERE nombre = 'Pelota de fútbol')    , (SELECT id FROM ALMACEN_DB.Ubicaciones WHERE nombre = 'P4E1'), (SELECT id FROM ALMACEN_DB.Ventas WHERE nombre = 'VTA-20250410-001'), 35    , CURDATE()    , CURDATE()          , 0           ),
                                  ((SELECT id FROM ALMACEN_DB.Productos WHERE nombre = 'Pelota de fútbol')    , (SELECT id FROM ALMACEN_DB.Ubicaciones WHERE nombre = 'P4E1'), NULL                                                                , 35    , CURDATE()    , CURDATE()          , 0           ),
                                  ((SELECT id FROM ALMACEN_DB.Productos WHERE nombre = 'Café orgánico')       , (SELECT id FROM ALMACEN_DB.Ubicaciones WHERE nombre = 'P4E3'), (SELECT id FROM ALMACEN_DB.Ventas WHERE nombre = 'VTA-20250420-001'), 18    , CURDATE()    , CURDATE()          , 0           ),
                                  ((SELECT id FROM ALMACEN_DB.Productos WHERE nombre = 'Café orgánico')       , (SELECT id FROM ALMACEN_DB.Ubicaciones WHERE nombre = 'P4E4'), NULL                                                                , 18    , CURDATE()    , CURDATE()          , 0           );